### ISSUE TITLE
Package SHAPER so that it is installable

### ISSUE THREAD

**Issue by matthewfeickert** [rikab/SHAPER#1]
👋 Hi. Thanks for making this Python implementation of SHAPER. At the moment it is not packaged, but a collection of locally importable files. It would be far more useful to have it be packaged in a small library so that it would be pip installable from the GitHub source code (and ideally from PyPI but that's a discussion for later).

Would you be open to a contribution through a PR that provides packaging?

**Comment by rikab** [comment]
Hi, yes we would be open to that! 
-Rikab

**Comment by rikab** [comment]
Hi, yes we  would be open to that! 
-Rikab
